# port
server:
  port: 8888
  servlet:
    context-path: /
    session:
      persistent: true
# db
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/webtraodoisp
    username: root
    password: manh1422000
    driver-class-name: org.mariadb.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    serialization:
      write-dates-as-timestamps: true

# uploading
data:
  path: F:/dev/source/res/

# logging
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG

session:
  login: USER_LOGIN
